export class SpecialityInsert {
    sp_id: number = 0;
    detail: string = '';
}
export class RefererInsert {
    refid: number =0;
    ac_code: number = 0;
    address: string = '';
    appointment: boolean = false;
    consult: boolean = false;
    consultid: number = 0;
    doctor: boolean = false;
    email: string = '';
    image: string = '';
    intime: string = '';
    min: number = 15;
    oncall: boolean = false;
    other: string = '';
    outtime: string = '';
    password: string = '';
    patho: boolean = false;
    present: string = '';
    professional: string = '';
    publication: string = '';
    qualification: string = '';
    radiologist: boolean = false;
    rate: number = 0;
    referer_type: number = 1;
    referer: string = '';
    refering: boolean = false;
    regno: string = '';
    sm_code: number = 0;
    sp_id: number = 0;
    specialized: string = '';
    status: string = 'Active';
    telephone: string = '';
    template_id: number = 0;
    templateid: number = 0;
    zoom_apikey: string = '';
    zoom_secretkey: string = '';
    zoom_user: string = '';
}